export const fallbackOpportunities = [
  {
    id: 'mock-1',
    title: "UX/UI Designer for Non-Profit",
    company: "Tech for Good Inc.",
    description: "Design user-centric interfaces for our non-profit platform to enhance social impact.",
    location: "Remote (Base: Kuala Lumpur)",
    type: "Volunteer",
    start_time: "2024-01-01",
    end_time: "2024-12-31",
    cause_tags: ["Technology", "Social Impact"],
    tags: ["Full Time", "Remote"],
    icon: "person",
    iconFilled: true,
    imageUrl: "https://images.unsplash.com/photo-1586717791821-3f44a5638d48?w=800&auto=format&fit=crop&q=60"
  },
  {
    id: 'mock-2',
    title: "Social Media Manager",
    company: "GreenFuture Org.",
    description: "Create engaging social media content to promote environmental awareness and initiatives.",
    location: "Remote (Base: Penang)",
    type: "Volunteer",
    start_time: "2024-02-01",
    end_time: "2024-08-31",
    cause_tags: ["Environment", "Marketing"],
    tags: ["Part Time", "Remote"],
    icon: "image",
    iconFilled: false,
    imageUrl: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&auto=format&fit=crop&q=60"
  },
  {
    id: 'mock-3',
    title: "Community Garden Volunteer",
    company: "Local Community Group",
    description: "Help cultivate a community garden, fostering local food security and green spaces.",
    location: "Taman Tugu, Persiaran Sultan Salahuddin, 50480 Kuala Lumpur",
    type: "Volunteer",
    start_time: "2024-03-15",
    end_time: "2024-10-31",
    cause_tags: ["Community", "Environment"],
    tags: ["Volunteer"],
    icon: "image",
    iconFilled: false,
    imageUrl: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&auto=format&fit=crop&q=60"
  },
  {
    id: 'mock-4',
    title: "Grant Writer",
    company: "Education for All Foundation",
    description: "Secure funding for educational programs by writing compelling grant proposals.",
    location: "Remote (Base: Johor Bahru)",
    type: "Contract",
    start_time: "2024-04-01",
    end_time: "2024-06-30",
    cause_tags: ["Education", "Fundraising"],
    tags: ["Contract", "Remote"],
    icon: "image",
    iconFilled: false,
    imageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=60"
  }
];
